### ISSUE TITLE
Chat Feature

### ISSUE THREAD

**Issue by menard-codes** [menard-codes/email-summarizer-ai#14]
Implement the RAG system and integrate it with the inbox to allow users to chat with the AI and ask any questions (either about the thread or any topic). The RAG will give context to the AI when the user asks something about the thread.

The Retrieval process will kick in when the user clicks on the `Start AI Chat`

## Tasks:

- [x] Keywords extraction
- [x] Google Search
- [x] Text Embeddings + retrieval
- [ ] Rag Chatbot (takes user query, output from google search, and retrieved relevant emails to generate response). Checkout Gemini's chat API, I guess it's more fitting to use that since it has history feature. Also, check out the chat stream, might be cool to use that.
- [ ] Chat endpoint
- [ ] Chatbot UI - start chat and chat interface

## Note
- I don't think I'm gonna need my MySQL database anymore, think about it, and remove if necessary.
